version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: tickets-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: tickets-adminer
    ports:
      - "8888:8080"
    depends_on:
      - db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: tickets-keycloak
    ports:
      - "9090:8080"
    command: start-dev --db=dev-file
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  postgres-data:
  keycloak-data: